name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy to Elastic Beanstalk
      run: |
        echo "Deploying to Elastic Beanstalk..."
        EB_BUCKET=elasticbeanstalk-us-east-2-522524811697
        aws s3 cp . s3://$EB_BUCKET/ --recursive --exclude ".git/*" --exclude ".github/*"
        aws elasticbeanstalk create-application-version --application-name your_application_name --version-label $GITHUB_SHA --source-bundle S3Bucket=$EB_BUCKET,S3Key=$GITHUB_SHA.zip
        aws elasticbeanstalk update-environment --application-name scatterbrain_sms_eb --environment-name scatterbrain_sms_eb-prod --version-label $GITHUB_SHA
