name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to Elastic Beanstalk
      run: |
        echo "Deploying to Elastic Beanstalk..."
        EB_BUCKET=elasticbeanstalk-us-east-2-522524811697
        ZIP_FILE=$GITHUB_SHA.zip
        # Create a zip file excluding unnecessary files
        zip -r $ZIP_FILE . -x ".git/*" -x ".github/*"
        # Upload the zip file to the S3 bucket
        aws s3 cp $ZIP_FILE s3://$EB_BUCKET/
        # Create a new application version using the uploaded zip file
        aws elasticbeanstalk create-application-version --application-name scatterbrain_sms --version-label $GITHUB_SHA --source-bundle S3Bucket=$EB_BUCKET,S3Key=$ZIP_FILE
        # Update the environment to use the new application version
        aws elasticbeanstalk update-environment --application-name scatterbrain_sms --environment-name Scatterbrainsms-prod --version-label $GITHUB_SHA
